name: buy_now_demo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.3
  flutter_statusbarcolor: ^0.2.3
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  conditional_builder: ^1.0.2
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.5
  get_it: ^5.0.6
  liquid_progress_indicator: ^0.3.2
  carousel_slider: ^3.0.0
  step_progress_indicator: ^1.0.0
  percent_indicator: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.5+1
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0


flutter_native_splash:
  color: "#ffffff"
#  background_image: "assets/images/Logo.jpg"
  image: assets/images/Logo.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/Logo.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/Logo.png
   - assets/translation/

  fonts:
    - family: Montesrrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family:  MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf